### ISSUE TITLE
Race condition in the fortran code

### ISSUE THREAD

**Issue by duerrsimon** [eth-cscs/PythonHPC#24]
There is a possible race condition for the tmp variables in the fortran codes supplied for the f90 files 
https://github.com/eth-cscs/PythonHPC/blob/master/f2py/distance-f90/euclidean.f90 
https://github.com/eth-cscs/PythonHPC/blob/master/f2py/distance-f90/cityblock.f90 

A possible fix would be to wrap the OMP PARALLEL like so 
` !$OMP PARALLEL DO PRIVATE(tmp)  `
as reported by @andersx

**Comment by rsarm** [comment]
Fixed in https://github.com/eth-cscs/PythonHPC/pull/33
Thanks @duerrsimon

**Comment by rsarm** [comment]
.
